import type { ColorMap } from '../types';

export const colors: ColorMap = {
	lightcoral: ['#F08080', 'light coral'],
	salmon: ['#FA8072', 'salmon'],
	darksalmon: ['#E9967A', 'dark salmon'],
	lightsalmon: ['#FFA07A', 'light salmon'],
	crimson: ['#DC143C', 'crimson'],
	red: ['#FF0000', 'red'],
	firebrick: ['#B22222', 'firebrick'],
	darkred: ['#8B0000', 'dark red'],
	pink: ['#FFC0CB', 'pink'],
	lightpink: ['#FFB6C1', 'light pink'],
	hotpink: ['#FF69B4', 'hot pink'],
	deeppink: ['#FF1493', 'deep pink'],
	mediumvioletred: ['#C71585', 'medium violet red'],
	palevioletred: ['#DB7093', 'pale violet red'],
	lightgray: ['#D3D3D3', 'light gray'],
	gray: ['#808080', 'gray'],
	darkgray: ['#A9A9A9', 'dark gray'],
	dimgrey: ['#696969', 'dim grey'],
	black: ['#000000', 'black'],
	white: ['#FFFFFF', 'white'],
	whitesmoke: ['#F5F5F5', 'white smoke'],
	snow: ['#FFFAFA', 'snow'],
	rosybrown: ['#BC8F8F', 'rosy brown'],
	brown: ['#A52A2A', 'brown'],
	maroon: ['#800000', 'maroon'],
	mistyrose: ['#FFE4E1', 'misty rose'],
	lavenderblush: ['#FFF0F5', 'lavender blush'],
	seashell: ['#FFF5EE', 'seashell'],
	lightgoldenrodyellow: ['#FAFAD2', 'light goldenrod yellow'],
	lemonchiffon: ['#FFFACD', 'lemon chiffon'],
	honeydew: ['#F0FFF0', 'honeydew'],
	floralwhite: ['#FFFAF0', 'floral white'],
	oldlace: ['#FDF5E6', 'old lace'],
	cornsilk: ['#FFF8DC', 'cornsilk'],
	linen: ['#FAF0E6', 'linen'],
	antiquewhite: ['#FAEBD7', 'antique white'],
	ivory: ['#FFFFF0', 'ivory'],
	beige: ['#F5F5DC', 'beige'],
	lightyellow: ['#FFFFE0', 'light yellow'],
	lightcyan: ['#E0FFFF', 'light cyan'],
	lavender: ['#E6E6FA', 'lavender'],
	thistle: ['#D8BFD8', 'thistle'],
	plum: ['#DDA0DD', 'plum'],
	violet: ['#EE82EE', 'violet'],
	orchid: ['#DA70D6', 'orchid'],
	mediumorchid: ['#BA55D3', 'medium orchid'],
	blueviolet: ['#8A2BE2', 'blue violet'],
	darkviolet: ['#9400D3', 'dark violet'],
	darkorchid: ['#9932CC', 'dark orchid'],
	darkmagenta: ['#8B008B', 'dark magenta'],
	purple: ['#800080', 'purple'],
	indigo: ['#4B0082', 'indigo'],
	darkslateblue: ['#483D8B', 'dark slate blue'],
	slateblue: ['#6A5ACD', 'slate blue'],
	mediumslateblue: ['#7B68EE', 'medium slate blue'],
	greenyellow: ['#ADFF2F', 'green yellow'],
	chartreuse: ['#7FFF00', 'chartreuse'],
	lawngreen: ['#7CFC00', 'lawn green'],
	lime: ['#00FF00', 'lime'],
	limegreen: ['#32CD32', 'lime green'],
	palegreen: ['#98FB98', 'pale green'],
	lightgreen: ['#90EE90', 'light green'],
	mediumseagreen: ['#3CB371', 'medium sea green'],
	seagreen: ['#2E8B57', 'sea green'],
	forestgreen: ['#228B22', 'forest green'],
	green: ['#008000', 'green'],
	darkgreen: ['#006400', 'dark green'],
	yellowgreen: ['#9ACD32', 'yellow green'],
	olivedrab: ['#6B8E23', 'olive drab'],
	olive: ['#808000', 'olive'],
	darkolivegreen: ['#556B2F', 'dark olive green'],
	mediumaquamarine: ['#66CDAA', 'medium aquamarine'],
	darkseagreen: ['#8FBC8F', 'dark sea green'],
	darkkhaki: ['#BDB76B', 'dark khaki'],
	gold: ['#FFD700', 'gold'],
	khaki: ['#F0E68C', 'khaki'],
	peachpuff: ['#FFDAB9', 'peach puff'],
	orange: ['#FFA500', 'orange'],
	darkorange: ['#FF8C00', 'dark orange'],
	orangered: ['#FF4500', 'orange red'],
	tomato: ['#FF6347', 'tomato'],
	coral: ['#FF7F50', 'coral'],
	darkgoldenrod: ['#B8860B', 'dark goldenrod'],
	peru: ['#CD853F', 'peru'],
	blanchedalmond: ['#FFEBCD', 'blanched almond'],
	bisque: ['#FFE4C4', 'bisque'],
	navajowhite: ['#FFDEAD', 'navajo white'],
	burlywood: ['#DEB887', 'burlywood'],
	tan: ['#D2B48C', 'tan'],
	chocolate: ['#D2691E', 'chocolate'],
	saddlebrown: ['#8B4513', 'saddle brown'],
	sienna: ['#A0522D', 'sienna'],
	sandybrown: ['#F4A460', 'sandy brown'],
	wheat: ['#F5DEB3', 'wheat'],
	silver: ['#C0C0C0', 'silver'],
	darkcyan: ['#008B8B', 'dark cyan'],
	cadetblue: ['#5F9EA0', 'cadet blue'],
	steelblue: ['#4682B4', 'steel blue'],
	lightsteelblue: ['#B0C4DE', 'light steel blue'],
	powderblue: ['#B0E0E6', 'powder blue'],
	lightblue: ['#ADD8E6', 'light blue'],
	skyblue: ['#87CEEB', 'sky blue'],
	lightskyblue: ['#87CEFA', 'light sky blue'],
	deepskyblue: ['#00BFFF', 'deep sky blue'],
	dodgerblue: ['#1E90FF', 'dodger blue'],
	cornflowerblue: ['#6495ED', 'cornflower blue'],
	royalblue: ['#4169E1', 'royal blue'],
	blue: ['#0000FF', 'blue'],
	mediumblue: ['#0000CD', 'medium blue'],
	darkblue: ['#00008B', 'dark blue'],
	navy: ['#000080', 'navy'],
	midnightblue: ['#191970', 'midnight blue'],
	lightseagreen: ['#20B2AA', 'light sea green'],
	darkturquoise: ['#00CED1', 'dark turquoise'],
	mediumturquoise: ['#48D1CC', 'medium turquoise'],
	turquoise: ['#40E0D0', 'turquoise'],
	aqua: ['#00FFFF', 'aqua'],
	cyan: ['#00FFFF', 'cyan'],
	paleturquoise: ['#AFEEEE', 'pale turquoise'],
	mediumspringgreen: ['#00FA9A', 'medium spring green'],
	springgreen: ['#00FF7F', 'spring green'],
	darkslategray: ['#2F4F4F', 'dark slate gray'],
	teal: ['#008080', 'teal'],
};
